"""Business Intelligence: automatically generated, data-backed observations.

Every insight here is computed directly from ledger/sales data at request
time — nothing is templated with placeholder numbers, and nothing is
generated by an LLM. Each insight carries `supporting_data` so a user (or
this codebase) can verify the claim independently.
"""
import datetime

from sqlalchemy import func
from sqlalchemy.orm import Session

from app.models.catalog import Brand, Product, ProductVariant
from app.models.sales import Sale, SaleItem
from app.services import aging_service


def _brand_sales_total(db: Session, start: datetime.date, end: datetime.date) -> dict[int, float]:
    rows = (
        db.query(Product.brand_id, func.sum(SaleItem.quantity * SaleItem.unit_price - SaleItem.discount))
        .select_from(SaleItem)
        .join(ProductVariant, ProductVariant.id == SaleItem.variant_id)
        .join(Product, Product.id == ProductVariant.product_id)
        .join(Sale, Sale.id == SaleItem.sale_id)
        .filter(Sale.sale_date >= start, Sale.sale_date <= end)
        .group_by(Product.brand_id)
        .all()
    )
    return {brand_id: float(total or 0) for brand_id, total in rows}


def brand_trend_insights(db: Session, as_of: datetime.date | None = None, period_days: int = 90) -> list[dict]:
    as_of = as_of or datetime.date.today()
    current_start = as_of - datetime.timedelta(days=period_days)
    prior_start = current_start - datetime.timedelta(days=period_days)
    prior_end = current_start - datetime.timedelta(days=1)

    current = _brand_sales_total(db, current_start, as_of)
    prior = _brand_sales_total(db, prior_start, prior_end)

    brands = {b.id: b.name for b in db.query(Brand).all()}
    insights = []
    for brand_id, name in brands.items():
        cur = current.get(brand_id, 0.0)
        prev = prior.get(brand_id, 0.0)
        if prev <= 0:
            continue
        change_pct = round(100 * (cur - prev) / prev, 1)
        if abs(change_pct) < 10:
            continue
        direction = "increased" if change_pct > 0 else "declined"
        insights.append(
            {
                "id": f"brand-trend-{brand_id}",
                "category": "brand_performance",
                "severity": "INFO" if change_pct > 0 else "WARNING",
                "text": f"{name} sales {direction} {abs(change_pct):.0f}% comparing the last "
                f"{period_days} days to the previous {period_days} days.",
                "supporting_data": {
                    "brand_id": brand_id,
                    "current_period_revenue": round(cur, 2),
                    "prior_period_revenue": round(prev, 2),
                    "change_pct": change_pct,
                    "current_period": [str(current_start), str(as_of)],
                    "prior_period": [str(prior_start), str(prior_end)],
                },
            }
        )
    return insights


def sales_concentration_insight(db: Session, as_of: datetime.date | None = None, period_days: int = 90) -> list[dict]:
    as_of = as_of or datetime.date.today()
    start = as_of - datetime.timedelta(days=period_days)
    rows = (
        db.query(SaleItem.variant_id, func.sum(SaleItem.quantity).label("qty"))
        .join(Sale, Sale.id == SaleItem.sale_id)
        .filter(Sale.sale_date >= start, Sale.sale_date <= as_of)
        .group_by(SaleItem.variant_id)
        .order_by(func.sum(SaleItem.quantity).desc())
        .all()
    )
    total_units = sum(q for _, q in rows)
    if total_units == 0:
        return []

    cumulative = 0
    top_skus = []
    for variant_id, qty in rows:
        cumulative += qty
        top_skus.append(variant_id)
        if cumulative / total_units >= 0.62:
            break

    pct = round(100 * cumulative / total_units, 0)
    return [
        {
            "id": "sales-concentration",
            "category": "concentration",
            "severity": "INFO",
            "text": f"These {len(top_skus)} SKUs account for {pct:.0f}% of unit sales in the last {period_days} days.",
            "supporting_data": {
                "period_days": period_days,
                "sku_count": len(top_skus),
                "variant_ids": top_skus[:50],
                "total_units_sold": total_units,
                "cumulative_units": cumulative,
            },
        }
    ]


def aging_value_insights(db: Session, as_of: datetime.date | None = None) -> list[dict]:
    as_of = as_of or datetime.date.today()
    detail = aging_service.compute_aging_detail(db, as_of)
    threshold_days = 180
    by_brand: dict[str, float] = {}
    for row in detail:
        if row["age_days"] >= threshold_days:
            by_brand[row["brand_name"]] = by_brand.get(row["brand_name"], 0.0) + row["inventory_value"]

    insights = []
    for brand_name, value in sorted(by_brand.items(), key=lambda kv: -kv[1]):
        if value <= 0:
            continue
        insights.append(
            {
                "id": f"aging-value-{brand_name}",
                "category": "aging",
                "severity": "WARNING",
                "text": f"{brand_name} stock older than {threshold_days} days represents an inventory cost of "
                f"{value:,.0f}.",
                "supporting_data": {"brand_name": brand_name, "threshold_days": threshold_days, "value": round(value, 2)},
            }
        )
    return insights


def generate_all_insights(db: Session, as_of: datetime.date | None = None) -> list[dict]:
    insights: list[dict] = []
    insights.extend(brand_trend_insights(db, as_of))
    insights.extend(sales_concentration_insight(db, as_of))
    insights.extend(aging_value_insights(db, as_of))
    return insights
