"""add sales allotments

Revision ID: 407d8e48032e
Revises: bd9ceba9bf6b
Create Date: 2026-09-06 11:56:08.150627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '407d8e48032e'
down_revision: Union[str, None] = 'bd9ceba9bf6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_allotments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesman_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('allotted_quantity', sa.Integer(), nullable=False),
    sa.Column('allotted_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.CheckConstraint('allotted_quantity > 0', name='ck_allotment_qty_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['salesman_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_allotments_allotted_date'), 'sales_allotments', ['allotted_date'], unique=False)
    op.create_index(op.f('ix_sales_allotments_salesman_id'), 'sales_allotments', ['salesman_id'], unique=False)
    op.create_index(op.f('ix_sales_allotments_variant_id'), 'sales_allotments', ['variant_id'], unique=False)
    op.create_index(op.f('ix_sales_allotments_warehouse_id'), 'sales_allotments', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_allotments_warehouse_id'), table_name='sales_allotments')
    op.drop_index(op.f('ix_sales_allotments_variant_id'), table_name='sales_allotments')
    op.drop_index(op.f('ix_sales_allotments_salesman_id'), table_name='sales_allotments')
    op.drop_index(op.f('ix_sales_allotments_allotted_date'), table_name='sales_allotments')
    op.drop_table('sales_allotments')
    # ### end Alembic commands ###
